### ISSUE TITLE
Google has released new XR SDK for Unity

### ISSUE THREAD

**Issue by sei0o** [aitc19x/VR-JC#20]
Look at this: https://developers.google.com/cardboard/develop/unity/quickstart

Or this: https://github.com/googlevr/cardboard-xr-plugin

We've been using outdated SDK (which is a pain for me) since there was no Unity-compatible one else, but Google released new Cardboard SDK for Unity a few weeks ago. It's already v.1.1.0 (stable?).

What do you think? Shall we move onto this while we don't have a lot of code, or do you say it's too early?

**Comment by TURX** [comment]
It is pretty new. I had not even found this on the Internet these months without official support for the old SDK. Maybe we can have a try after merging the existing two pull requests, or you can just create a dedicated pull request for the new SDK for now and merge it to the master branch with the two pull requests, because the two PRs has nothing to do with Google VR.

**Comment by TURX** [comment]
It is pretty new. I had not even found this on the Internet these months without official support for the old SDK. Maybe we can have a try after merging the existing two pull requests, or you can just create a dedicated pull request for the new SDK for now and merge it to the master branch with the two pull requests, because the two PRs has nothing to do with Google VR.

**Comment by TURX** [comment]
Fixed in ac5f374.
